from hashmap import HashMap
from treeNode import TreeNode
from min_heap import MinHeap

heap = MinHeap()
heap.add(5)
heap.add(1)
heap.add(200)
heap.add(143)
heap.add(43)
heap.add(98)
heap.add(1000)
heap.add(0)
heap.add(-3)
heap.add(10)
heap.add(11)

print()
print()
heap.retrieve_min()
heap.retrieve_min()
heap.retrieve_min()
heap.retrieve_min()
heap.retrieve_min()
heap.retrieve_min()
heap.retrieve_min()
heap.retrieve_min()
heap.retrieve_min()
heap.retrieve_min()
heap.retrieve_min()
heap.retrieve_min()